### ISSUE TITLE
Fail to initialize due to unknown Zone Id

### ISSUE THREAD

**Issue by jacek99** [RomanIakovlev/timeshape#12]
Fails to initialize all world data

  private static final TimeZoneEngine engine = TimeZoneEngine.initialize();

With Java 8:

Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: America/Fort_Nelson
	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at net.iakovlev.timeshape.Index.lambda$build$5(Index.java:81)
	at net.iakovlev.timeshape.Index$$Lambda$713/437255067.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.iakovlev.timeshape.Index.build(Index.java:68)
	at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:88)
	at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:59)

**Comment by RomanIakovlev** [comment]
Also, just to confirm, are you using the latest version of Timeshape, the `2018d.4`?

**Comment by jacek99** [comment]
Hi, you were correct, it was a box with an old JVM (1.8.51), once we pointed it to latest it worked correctly.

However, I think it would still be good (to future proof it), that this gets caught as an exception and handled gracefully. Right now it blows up the whole engine and stops an app from booting up.

Probably more graceful would be log ERROR and in case someone asks for a lat/long in this area, then return Optional.empty() from *engine.query*

**Comment by RomanIakovlev** [comment]
Ok, thanks for confirmation. I totally agree it's not nice to throw an exception there, and that it should be fixed. 

I have the following fix in mind: the instance of `TimeZoneEngine` should expose a collection of time zones it couldn't recognize during initialization. When it encounters an unknown zone id during initialization, it just skips adding it into the index, but adds it into that `unrecognized` collection instead, which library user can inspect after initialization and make a decision on how to proceed.

I'd rather not add any logging into the library itself, but leave it to the user to analyze the unrecognized zones and either log them or do something else.

Feedback on this idea is welcome, and a pull request would be definitely much appreciated! :)

**Comment by jacek99** [comment]
Well, I think it should explicitly log an ERROR and alert the dev team they are running on an outdated JVM and to do something about this. Otherwise this will just go on undetected and probably just hit an error downstream during some business logic relevant to some lat/long

Personally I would log ERROR as this is the type of issue that should be escalated to the dev team using the library, IMHO

**Comment by RomanIakovlev** [comment]
Hi @jacek99, I've just published a new version (2018d.5-SNAPSHOT) to Sonatype Snapshots repository. In this version I've enabled the logging, pretty much along the lines of your suggestion. I would appreciate if you give it a try and share your feedback.

**Comment by RomanIakovlev** [comment]
Ok, I've actually went ahead and released 2018d.5 where this change is merged. Closing this issue, please create another one if you want to continue discussion on this topic.
