### ISSUE TITLE
OpenJDK 8.0 doesn't load timeshape 

### ISSUE THREAD

**Issue by juarezr** [RomanIakovlev/timeshape#122]
# OpenJDK 8.0 doesn't load timeshape

- Code compiles.
- But throws a Runtime error:

```bash
net/iakovlev/timeshape/TimeZoneEngine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

## Which Timeshape version are you using?

```gradle
dependencies {
    implementation(project(':common'))
    implementation(project(':domain'))

    implementation(group: 'org.apache.commons', name: 'commons-lang3', version: '[3.7,4)')
    implementation(group: 'org.apache.commons', name: 'commons-math3', version: '[3.6.1,4)')

    implementation(group: 'net.time4j', name: 'time4j-base', version: '[5.9,6)')
    implementation(group: 'net.time4j', name: 'time4j-tzdata', version: '[5.0-2023b,6)')

    implementation(group: 'net.iakovlev', name: 'timeshape', version: '[2022g.17,)')

}
```

## Which Java version are you using?

```bash
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u372-ga~us1-0ubuntu1~23.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

## If you upgrade to the latest Java minor version, does it still fail?

Previous working version:

``` gradle
    // group: 'net.iakovlev', name: 'timeshape', version: '[2020d.11,)'
```

## Additional information
E.g. if this used to work in some previous Timeshape version or any other significant facts.

```java

    public static void initTimeZoneSouthAmerica() {

        // Shapes from South America Rectangle
        timeZoneEngine = TimeZoneEngine.initialize(-56.0, -83.0, 13.0, -32.0, true);
    }
```

```text
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.UnsupportedClassVersionError: net/iakovlev/timeshape/TimeZoneEngine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.movida.base.TimeZoneCommon.initTimeZoneSouthAmerica(TimeZoneCommon.java:110)
TimeZoneCommon.java:110
	at com.movida.base.TimeZoneCommon.initTimeZone(TimeZoneCommon.java:85)
TimeZoneCommon.java:85
	at com.movida.base.TimeZoneCommon.queryZoneNameFrom(TimeZoneCommon.java:40)
TimeZoneCommon.java:40
	at com.movida.base.TimeZoneCommon.getLocalDateTimeAt(TimeZoneCommon.java:30)
TimeZoneCommon.java:30
```

**Comment by juarezr** [comment]
Latest version working with Java 8:


```gradle
    implementation(group: 'net.iakovlev', name: 'timeshape', version: '2022f.15')
```gradle

**Comment by RomanIakovlev** [comment]
Thanks for reporting, I've only noticed this now. It might be the case I've inadvertently changed the Java version used to build Timeshape when I've migrated to GitHub Actions to build it. I'll have a look.

**Comment by juarezr** [comment]
Maybe it could be fixed by adding the following to `build.sbt`:

```scala
scalacOptions += "-target:jvm-1.8"
```

**Comment by RomanIakovlev** [comment]
Let's keep this open for now, until we have a confirmation this works as intended.

**Comment by juarezr** [comment]
Humm, It didn't work:

```text
+-------------------+-----------+-----------+----------+
|  java / timeshape | 1.8.0_382 | 11.0.20.1 | 17.0.8.1 |
+===================+===========+===========+==========+
|      2022f.15     |     Ok    |     Ok    |    Ok    |
+-------------------+-----------+-----------+----------+
|      2022g.17     |   Fails   |     Ok    |    Ok    |
+-------------------+-----------+-----------+----------+
| 2022g.18-SNAPSHOT |   Fails   |     Ok    |    Ok    |
+-------------------+-----------+-----------+----------+
```

Meanwhile, I got my code migrated to Java 11.

**Comment by RomanIakovlev** [comment]
Thanks for taking a look still, @juarezr. I think going to Java 11 is the right way, Java 8 is way too old, but I can sympathise with those who cannot easily migrate. 

I'm sure there is a way to enable Java 8 build, it's just the setting for that is not straightforward to find. I'll see what I can do.
