### ISSUE TITLE
zstd-jni-1.5.0-4 issue

### ISSUE THREAD

**Issue by luciangruiaro** [RomanIakovlev/timeshape#88]
I tried upgrading to latest version and still getting this issue on CentOS. 
It is working fine on Windows. Any idea please?

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.0-410397134098366552495.so: /tmp/libzstd-jni-1.5.0-410397134098366552495.so: failed to map segment from shared object: Operation not permitted
no zstd-jni-1.5.0-4 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni-1.5.0-4.so or load zstd-jni-1.5.0-4 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.0-4 in your system.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
        at java.base/java.lang.System.loadLibrary(System.java:1871)
        at com.github.luben.zstd.util.Native.load(Native.java:124)
        at com.github.luben.zstd.util.Native.load(Native.java:55)
        at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
        at com.github.luben.zstd.ZstdInputStream.<init>(ZstdInputStream.java:24)
        at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:235)
        at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:153)
`

**Comment by RomanIakovlev** [comment]
Hi, thanks for reporting this. Do you see this problem on older versions of Timeshape as well, or only on the latest one?

**Comment by luciangruiaro** [comment]
Hey. Yes, I tried with 3 older versions and had the same issue.

**Comment by chiralsoftware** [comment]
I'm having this issue when using timeshape in a Spring Boot application. The Spring Boot application is generating a WAR file which we are running in Apache Tomcat. All is fine until I try to run Tomcat as non-root using jsvc. Then I get an error, the most relevant part being:

```
ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.5-11: No such file or directory
                at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
                at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:218)

```

At this point options are a) find some way to run as non-root without jsvc b) figure out what the magical option is on jsvc to let it load that file. Neither of them are great. I'm sorry to say but the ideal would be for the excellent timeshape library to use some other compression that doesn't trigger JNI. JNI should be deprecated at this point and will be disabled by default in JDK 24. I realize that built-in algs are zip and gzip whcih are both really old at this point, but from a minimizing pain point of view, they would be really easier than dealing with JNI.

**Comment by RomanIakovlev** [comment]
Thanks for your feedback @chiralsoftware. I'm glad your issue is resolved, and I understand the pain of dealing with JNI and restrictive environments. 

The thing is, Timeshape tries to fit many different use cases at the same time. It's available on Android as well, which means it's deployed to mobile devices via app stores, where size and initialization times matter a lot. I have put a lot of efforts in making the main Timeshape JAR as small as possible to support the mobile use case, and I'd be hesitant to lose those efficiencies by being forced into an ancient compression algorithm.

That being said, I'm not deeply familiar with the state of the art in modern compression technologies in Java. If there is some alternative, non-JNI, open source implementation that gives similar result in the artifact size (within some reasonable margin, let's say 5%), I'd definitely consider switching to it.

P.S. from what I understand reading [JEP 472](https://openjdk.org/jeps/472), it will just print warnings on JNI usage, not throw an exception yet (that's slated for future, yet unknown Java releases). Your point is still valid though, at some later time we'll need a solution (at least in the form of documentation) for those running Timeshape on the latest Java release.

**Comment by chiralsoftware** [comment]
There seems to be [this library](https://github.com/airlift/aircompressor/tree/master) that has pure Java implementations of several options, including zstd, which is the current best general-purpose compression algorithm, and the code is Apache licensed. I do appreciate what you are saying, on Android, JAR (APK) size matters and speed matters, and a JNI based approach probably beats anything else on that.

Here's a [recent and quite complete performance evaluation](https://dkomanov.medium.com/java-compression-performance-fb373078cfde) of the various options, including comparing JNI and pure Java implementations.
